# Generated by Django 5.2.12 on 2026-03-28 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bin_size', models.IntegerField()),
                ('alpha', models.FloatField()),
                ('test_set_index', models.IntegerField()),
                ('row_index', models.IntegerField()),
                ('predicted', models.FloatField()),
                ('actual', models.FloatField()),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('bin_size', 'alpha', 'test_set_index', 'row_index'), name='unique_prediction')],
            },
        ),
    ]
