# Generated by Django 5.1.1 on 2026-04-08 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_datasetrecord'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DatasetRecord',
        ),
    ]
